### ISSUE TITLE
Variant search

### ISSUE THREAD

**Issue by odera89** [SatelCreative/crisp#6]
Hi. Can you help me a bit that how can I search by variant. I have products size added to Variant, and I want to search through it. Can I somehowe?

Many thanks!

**Comment by qw-in** [comment]
Sounds like you may be wanting to add extra fields to the search? I'm not sure exactly where on the variant you are storing the sizing data but here is a list of the fields that are searchable in Shopify

https://help.shopify.com/en/manual/sell-online/online-store/storefront-search#searching-specific-fields

Since the last version of Crisp was released, it looks like the way this is done in Shopify has changed, but you could try setting `fields` on the search object to include all of those linked above and see if it works

(little rusty on the syntax)
```js
const search = Search({
  //... 
  fields: ["title", /* etc */, "variants.title"]
})
```
```

**Comment by odera89** [comment]
Thanks for suggestion!
